# Generated by Django 3.2.25 on 2025-04-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_auto_20250418_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='energydata',
            options={'ordering': ['year']},
        ),
        migrations.AlterField(
            model_name='country',
            name='renewable_share',
            field=models.FloatField(help_text='Renewable energy share in 2015 (%)'),
        ),
        migrations.AlterUniqueTogether(
            name='energydata',
            unique_together={('country', 'year')},
        ),
    ]
