# Generated by Django 3.2.25 on 2025-04-21 18:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

def transfer_data(apps, schema_editor):
    Country = apps.get_model('energy', 'Country')
    EnergyData = apps.get_model('energy', 'EnergyData')
    
    for country in Country.objects.exclude(renewable_share__isnull=True):
        EnergyData.objects.create(
            country=country,
            year=2015, 
            renewable_share=country.renewable_share
        )

class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_auto_20250421_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='energydata',
            options={'get_latest_by': 'year', 'ordering': ['-year'], 'verbose_name': 'Energy Data', 'verbose_name_plural': 'Energy Dataset'},
        ),
        migrations.RunPython(transfer_data),
        migrations.RemoveField(
            model_name='country',
            name='renewable_share',
        ),
        migrations.RemoveField(
            model_name='country',
            name='type',
        ),
        migrations.AddField(
            model_name='energydata',
            name='fossil_share',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fossil Fuel Share (%)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='income_group',
            field=models.CharField(choices=[('L', 'Low income'), ('LM', 'Lower middle income'), ('UM', 'Upper middle income'), ('H', 'High income')], default='Unknown', max_length=30, verbose_name='Income Group'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.country', verbose_name='Related Country'),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='renewable_share',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Renewable Energy Share (%)'),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2005), django.core.validators.MaxValueValidator(2020)], verbose_name='Year'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['region'], name='energy_coun_region_e5d8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['income_group'], name='energy_coun_income__9be668_idx'),
        ),
    ]