# Generated by Django 3.2.25 on 2025-04-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_auto_20250421_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='income_group',
            field=models.CharField(blank=True, choices=[('high', 'High income'), ('low', 'Low income'), ('lower_middle', 'Lower middle income'), ('upper_middle', 'Upper middle income')], max_length=20, null=True),
        ),
    ]
