# Generated by Django 3.2.25 on 2025-04-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0005_alter_country_income_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='income_group',
            field=models.CharField(blank=True, choices=[('High income', 'High income'), ('Low income', 'Low income'), ('Lower middle', 'Lower middle income'), ('Upper middle', 'Upper middle income')], max_length=20, null=True),
        ),
    ]
