# Generated by Django 3.2.25 on 2025-04-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_alter_energydata_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='type',
            field=models.CharField(default='country', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(default='UNKOWN', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='income_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
